name: demo
	on:
	  workflow_dispatch:
jobs:
  manual_deploy:
    runs-on: self-hosted
    environment: dev
    steps: 
      - uses: actions/checkout@v2
      - run: export PATH=/root/.nvm/versions/node/v18.10.0/bin:${PATH}
      - run: echo "$PATH"
      - run: cd /home/demo          
      - run: git pull origin development
      - run: export PM2_HOME="/root/.pm2"; pm2 restart demo
        env:
          CI: true
